# Generated by Django 4.2 on 2023-04-25 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('duration', models.IntegerField(verbose_name='la duration')),
                ('lyrics', models.TextField(verbose_name='lyrics')),
            ],
        ),
    ]
